### ISSUE TITLE
UnfoldFlowSpecAutoFusingOn failed

### ISSUE THREAD

**Issue by raboof** [akka/akka-stream-contrib#108]
```
[info] UnfoldFlowSpecAutoFusingOn:
[info] unfoldFlow
[info]   should unfold Collatz conjecture with a sequence of 111 elements
[info]   - should with flow (207 milliseconds)
[info]   - should with buffered flow (158 milliseconds)
[info]   - should with function (117 milliseconds)
[info]   should increment integers & handle KillSwitch
[info]     should with simple flow
[info]       should killSwitch prepended to flow
[info]       - should fail instantly when aborted (11 milliseconds)
[info]       - should fail when inner stream is canceled and pulled before completion *** FAILED *** (23 milliseconds)
[info]         java.lang.AssertionError: assertion failed: expected OnError(java.lang.Exception: KILL!
[info] 	at akka.stream.contrib.UnfoldFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$11.apply(UnfoldFlowSpec.scala:99)
[info] 	at akka.stream.contrib.UnfoldFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$11.apply(UnfoldFlowSpec.scala:97)
```

**Comment by hochgi** [comment]
@raboof do you know which change broke it?
Any chance `reference.conf` settings were overridden?
https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/resources/reference.conf

If configured time isn't enough, stage will fail with an `IllegalArgumentException` instead of the expected exception.   
(this is the only guess I have right now as to why it failed...)  

P.S.  
We're running with unfoldFlow in production for several months now:  
https://github.com/thomsonreuters/CM-Well  
 and no failures in it so far...  

Will try to see if I can reproduce it later.

**Comment by hochgi** [comment]
Well, only reproducible in 2.5(.3), and not deterministically.  
Fail on both `on` & `off` fusing (which doesn't matter anyway, since 2.5.X has fusing always enabled, and setting is deprecated).  
When all other tests ignored, passes for both `on` & `off`.

**Comment by hochgi** [comment]
Added some debug prints, and got the following findings: 
test code:
```scala
val (killSwitch, sink) = source.toMat(TestSink.probe)(Keep.both).run()
val kill = new Exception("KILL!")
sink.ensureSubscription()
killSwitch.abort(kill)
sink.request(1)
sink.expectError(kill)
```
expectations:
```none
killSwitch invoked, causing a race condition between upstream & downstream cancellations:

scenario 1:
killSwitch invoked -> flow propagates termination-> InHandler.onUpstreamFailure is invoked and stream terminates properly.
scenario 2: 
killSwitch invoked -> feedback's OutHandler.onDownstreamFinish -> set scheduler to configured 1 minute to allow scenario 1 to finish properly
```
in any case, stream should have been canceled. 
what actually happened was:
```none
1- killSwitch invoked
2- test request(1) -> output's onPull -> feedback's onPull -> onPush -> push
3- feedback's OutHandler.onDownstreamFinish is invoked
4- InHandler's onUpstreamFailure is invoked
```
The problem is that killSwitch is still operational after being aborted.

**This seems like a bug in KillSwitch!**

After being aborted, it shouldn't have handled both `onPull` & `onPush`.

**Comment by johanandren** [comment]
`abort()` is not synchronous, so you cannot be sure the command to abort passes the asynchronous boundary before the request and emit happens. That's a race that is hard to workaround I'm afraid. Only thing I can think of making it less racy is the sleep before requesting.

**Comment by hochgi** [comment]
@johanandren so is this test even needed? perhaps we should just drop the test entirely...

**Comment by johanandren** [comment]
Sounds like `should fail instantly when aborted` should cover that it works, but I didn't look into the code. 

I'm not quite sure why there needs to be special tests for killswitch here, it doesn't do anything a cancelled/failed/completed stream does not already do.

**Comment by hochgi** [comment]
Since the unfold source closes over a given unknown flow, we need to take careful care of flow termination.
We closes over the given flow from both upstream and downstream.
So, if we get `onDownstreamFinish()` being called, we can't (yet) know how to terminate.
So we wait for a configurable amount of time, and wait for either `onUpstreamFinish()` or `onUpstreamFailure(ex)`.
If configured time exceeded, we terminate with `fail(IllegalStateException)`.

Because of that, there's difference between KillSwitch being appended or prepended to flow. (maybe a test holding downstream fail explicitly should be added).

Also, the reason this test was added, was to check the following scenario:

1. Inner flow send termination as downstream (`onDownstreamFinish()` is called)
2. We wait (1m by default) to get flow termination as `onUpstreamFinish()` or `onUpstreamFailure(ex)`
3. Source is being pulled
4. We get `onUpstreamFailure(ex)`

It's a delicate edge case, and IIRC, I had a bug, pull changed the state in a way such that flow didn't terminate.

**Comment by johanandren** [comment]
Can you perhaps put two probes in there instead, by using `Flow.fromSinkAndSource` and have full control over what goes on in the inner flow?

**Comment by hochgi** [comment]
Good idea. Will try to get to it soon and open a quick PR.
