### ISSUE TITLE
Failed CassandraSourceSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka-stream-contrib#70]
This test fails quite frequently in CI validation.

```
[info] - must stream the result of a Cassandra statement with several pages *** FAILED *** (473 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 15 milliseconds between each query. (CassandraSourceSpec.scala:75)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:546)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:558)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:74)
[info]   at akka.stream.contrib.cassandra.CassandraSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(CassandraSourceSpec.scala:75)
[info]   at akka.stream.contrib.cassandra.CassandraSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(CassandraSourceSpec.scala:69)
[info]   at akka.stream.contrib.cassandra.CassandraSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(CassandraSourceSpec.scala:69)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by 2m** [comment]
Most of the TravisCI builds that failed because of this have been restarted and can not be found in the build history. I have found this one for logs: https://travis-ci.org/akka/akka-stream-contrib/builds/161912879 

@atamborrino do you have an idea why this could be failing? Should we just increase the timeout?

**Comment by atamborrino** [comment]
I think the test timeout may be the issue yeah.
